
phase: 'train'
# phase: 'test'
load_yaml: True
gpu: '0'

# pretraining setting
continue_train: False
# continue_train: True
ckpt_name: 'LSSL_42100.pth.tar'
# ckpt_name: 'model_best.pth.tar'
# ckpt_name: 'pretrained_model_best.pth.tar'      ###################
# ckpt_name: 'epoch197.pth.tar'

# dataset
data_type: 'pair'
dataset_name: 'CP'
data_path: '/media/andjela/SeagatePor1/CP/data/CP/'
# img_file_name: 'ADNI_longitudinal_img.h5'
img_file_name: 'CP_longitudinal_img.h5'
noimg_file_name: 'CP_longitudinal_noimg.h5'
subj_list_postfix: 'CP'          ###################


# training setting
epochs: 100
batch_size: 64
num_fold: 5
fold: 0
shuffle: True
# lr: 0.0005
lr: 0.0001
aug: True
# aug: False
# use_feature: ['z', 'delta_z']
use_feature: ['z']
# pos_weight: [1.4]
pos_weight: [1.5]
# pos_weight: [1.1]
# froze_encoder: True
froze_encoder: False
froze_dir_a: False                  ###################

# model setting
latent_size: 512
num_neighbours: 5
agg_method: 'gaussian'

# model_name: 'LDDM'
# model_name: 'LDD'       ####################
model_name: 'LSSL'       # longitudinal direction disentangle
# model_name: 'CLS'       # encoder + classifier
lambda_recon: 4.
lambda_dir_a: 2.
lambda_dir_d: 1.
lambda_cls: 0.
lambda_kl: 1.
lambda_penalty: 1.      ###################
lambda_reg: 0.

lambda_dir: 0.
lambda_dis: 0.

enc_dec_type: 'simple'
# enc_dec_type: 'normal'
# enc_dec_type: 'simple-mapping'
is_mapping: False

# LDD on ADNI
ckpt_timelabel: '2022_2_6_18_21'
# ckpt_timelabel: '2021_4_13_10_43'         # step 1: LSSL on all
# ckpt_timelabel: '2021_5_17_18_16'           # step 1: LSSL, based on 2021_4_13_10_43, froze encoder
# ckpt_timelabel: '2021_4_22_22_14'         # step 2: LDD, based on LSSL on all 2021_4_13_10_43
# ckpt_timelabel: '2021_4_22_22_19'         # step 3: LDD, based on 2021_4_22_22_14 ######### 4/22
# ckpt_timelabel: '2021_5_17_18_28'         # step 3: LDD, based on 2021_4_22_22_19, froze encoder

# ckpt_timelabel: '2021_5_3_22_38'            # step 4: LDD, based on 2021_4_22_22_14, 97685, gpu 1

# ckpt_timelabel: '2021_5_3_22_11'            # step 2: LDD, based on LSSL on all 2021_4_13_10_43, only use ad to regularize
# ckpt_timelabel: '2021_5_3_22_12'            # step 3: LDD, based on 2021_5_3_22_11, only use ad to regularize

