
phase: 'train'
# phase: 'test'
load_yaml: True
gpu: '1'

# pretraining setting
# continue_train: False
continue_train: True
# ckpt_name: 'model_best.pth.tar'
ckpt_name: 'pretrained_model_best.pth.tar'      ###################

# dataset
data_type: 'pair'
dataset_name: 'ADNI'
data_path: '../data/ADNI/'
# img_file_name: 'ADNI_longitudinal_img.h5'
img_file_name: 'ADNI_longitudinal_img_aug.h5'
noimg_file_name: 'ADNI_longitudinal_noimg.h5'
subj_list_postfix: 'NC_AD_pMCI_sMCI'          ###################
# subj_list_postfix: 'NC'
# subj_list_postfix: 'NC_AD'
# subj_list_postfix: 'pMCI_sMCI'

# data_type: 'pair'
# data_type: 'single'
# dataset_name: 'LAB'
# data_path: '../data/LAB/'
# # img_file_name: 'LAB_longitudinal_img.h5'
# img_file_name: 'LAB_longitudinal_img_aug.h5'
# noimg_file_name: 'LAB_longitudinal_noimg.h5'
# # subj_list_postfix: 'C_E_HE_far'
# # subj_list_postfix: 'C_E_HE'
# # subj_list_postfix: 'C_single'
# subj_list_postfix: 'C'

# training setting
epochs: 200
batch_size: 32
num_fold: 5
fold: 0
shuffle: True
# lr: 0.0005
lr: 0.0001
# aug: True
aug: False
# use_feature: ['z', 'delta_z']
use_feature: ['z']
# pos_weight: [1.4]
pos_weight: [1.5]
# pos_weight: [1.1]
# froze_encoder: True
froze_encoder: False
froze_dir_a: True                  ###################

# model setting
latent_size: 1024
num_neighbours: 5
agg_method: 'gaussian'

model_name: 'LDD'       ####################
# model_name: 'LSSL'       # longitudinal direction disentangle
# model_name: 'CLS'       # encoder + classifier
lambda_recon: 2.
lambda_dir_a: 1.
lambda_dir_d: 1.
lambda_cls: 0.
lambda_kl: 1.
lambda_penalty: 1.      ###################

lambda_dir: 1.
lambda_dis: 0.


# LSP
# ckpt_timelabel: '2021_4_13_11_17'         # LDD, no kl
# ckpt_timelabel: '2021_4_18_23_39'         # LDD, with kl
# ckpt_timelabel: '2021_4_13_10_43'         # LSSL on all
# ckpt_timelabel: '2021_4_18_23_41'         # LDD, based on LSSL on all
# ckpt_timelabel: '2021_4_22_22_12'         # LDD, based on LSSL on all, with new kl and penalty
# ckpt_timelabel: '2021_4_22_22_13'         # LDD, based on LSSL on all, with new kl and no penalty
# ckpt_timelabel: '2021_4_22_22_14'         # LDD, based on LSSL on all, with no kl and no penalty
ckpt_timelabel: '2021_4_22_22_15'         # LDD, based on LSSL on all, with new kl and penalty
